### ISSUE TITLE
Request for column header info for example data file

### ISSUE THREAD

**Issue by SRHilz** [jieliu6/THEMIS#2]
Would you be able to add descriptors for each column of the example data input file, combinedData_01-1-B2_01-2-B2_01-4-B3.txt, in either the tutorial.md file or, alternatively, as a README in the data folder? This file has no column header, and so it is a bit difficult to confirm that I correctly understand what data is in each column.

This would be very helpful for making the tool more accessible for others to use, so that potential users can confirm our input is in the correct format.

Thanks!

**Comment by jieliu6** [comment]
Column 1: chromosome
Column 2: base pair position
Column 3-5: allelic ratios in the three biopsies
Column 6-8: log ratios in the three biopsies
Column 9: whether this genomic position is germline heterozygous or germline homozygous
